"""Source: a Google AI Mode page saved from Chrome ("Save Page As → Web Page,
Complete"), or the slimmed copy of it that slim_google_page.py writes.

Unlike google_export (the "AI Chat Exporter" extension's markdown), the saved
page is the live DOM, so it carries what the extension drops: the time of
every prompt, every turn up to the moment of saving, and the formulas.
"Web Page, HTML Only" does NOT work — Chrome then saves the server's first
HTML, in which no turn has been rendered yet.

What is read, per turn (`data-scope-id="turn"`):
- the prompt — from the hidden "AI Mode reply for <prompt>" heading
  (REPLY_HEADING_CLASS), the one place its line breaks survive: the visible
  span (PROMPT_CLASS, the fallback) has them stripped ("слово\\n\\nВсё" shows
  as "словоВсё");
- its time — "3:53 p.m." in the viewer's locale, minutes only, no date
  (TIME_CLASS); responses carry no time of their own;
- the response — the subtree under RESPONSE_CLASS, rendered to markdown here.

The date is not on the page at all. It is anchored to the moment the tab
opened the thread, which Chrome records in the `<!-- saved from url=... -->`
comment at the top of the file (the `sxsrf` parameter ends in a millisecond
timestamp); each time a prompt's time goes backwards, the next day begins.
This is wrong when the thread was begun on an earlier day than the tab was
opened, so slim_google_page.py can pin the first turn's date explicitly
(DATE_META), which then wins over the anchor.

Formulas come as "chips" (CHIP_CLASS) holding three copies of the same
formula: MathML, its spoken annotation ("2 p sub 10"), and SVG glyphs. A chip
is rendered from the MathML when it has any, otherwise from the glyphs, whose
smaller font and vertical shift mark a superscript or subscript — never from
the annotation. Citations become `[Source](url)` after the sentence they
back; the "+3" count of further sources is dropped, as their links are not
on the page.

The class names below are generated by Google's build and drift between
releases; when a saved page stops converting, they are the first suspects.
Everything is stdlib — the tests run with pytest alone.
"""

import html
import re
import sys
import unicodedata
from datetime import date, datetime, timedelta
from html.parser import HTMLParser
from pathlib import Path

from turns import Atom

TURN_ATTR = ("data-scope-id", "turn")
REPLY_HEADING_CLASS = "MheKwc"
REPLY_FOR = "AI Mode reply for "
PROMPT_CLASS = "VndcI"
TIME_CLASS = "kwdzO"
RESPONSE_CLASS = "mZJni"
SECTION_HEADING_CLASS = "otQkpb"
CHIP_CLASS = "dteT0b"
DISPLAY_CHIP_CLASS = "cPGBZb"  # wraps a chip set on its own line
CITATION_CLASS = "WBgIic"
CITATION_LINK_CLASS = "PMDqCb"
CITATION_SOURCE_CLASS = "QNca8b"
CODE_BLOCK_CLASS = "aiModeUiCodeBlock__Container"
CODE_LANG_CLASS = "a2TNg"
# UI chrome inside a response: copy/share/feedback widgets, the share dialog,
# the legal footer, "Use code with caution.", a citation with no link
JUNK_CLASSES = {"DBd2Wb", "zkL70c", "oLpkLe", "VT1SYd", "iMHp6c", "DHPVt"}
JUNK_TAGS = {"script", "style", "link", "img", "svg", "button", "textarea", "aside", "input", "noscript", "template"}

DATE_META = "duet-first-turn-date"
SAVED_FROM = re.compile(r"<!-- saved from url=\(\d+\)(\S+) -->")
SXSRF_MS = re.compile(r"sxsrf=[^&\s]*?(?:%3A|:)(\d{13})")
TIME = re.compile(r"(\d{1,2}):(\d{2})(?:\s*([ap])\.?\s*m\.?)?", re.IGNORECASE)

VOID = {"area", "base", "br", "col", "embed", "hr", "img", "input", "link", "meta", "source", "track", "wbr", "param"}
INLINE_TAGS = {"span", "strong", "b", "em", "i", "a", "code", "mark", "u", "br", "sub", "sup", "s", "del", "small", "q", "abbr"}


# --- a minimal DOM -------------------------------------------------------------


class Node:
    __slots__ = ("tag", "attrs", "kids", "parent")

    def __init__(self, tag: str, attrs: list, parent: "Node | None"):
        self.tag = tag
        self.attrs = {k: (v or "") for k, v in attrs}
        self.kids: list = []
        self.parent = parent

    def classes(self) -> set[str]:
        return set(self.attrs.get("class", "").split())

    def has_class(self, name: str) -> bool:
        return name in self.classes()

    def walk(self):
        yield self
        for kid in self.kids:
            if isinstance(kid, Node):
                yield from kid.walk()

    def find(self, pred) -> "Node | None":
        return next((n for n in self.walk() if n is not self and pred(n)), None)

    def raw_text(self) -> str:
        return "".join(k if isinstance(k, str) else k.raw_text() for k in self.kids)


class _TreeBuilder(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.root = Node("#root", [], None)
        self.cur = self.root

    def handle_starttag(self, tag, attrs):
        node = Node(tag, attrs, self.cur)
        self.cur.kids.append(node)
        if tag not in VOID:
            self.cur = node

    def handle_startendtag(self, tag, attrs):
        self.cur.kids.append(Node(tag, attrs, self.cur))

    def handle_endtag(self, tag):
        node = self.cur
        while node is not None and node.tag != tag:
            node = node.parent
        if node is not None and node.parent is not None:
            self.cur = node.parent

    def handle_data(self, data):
        self.cur.kids.append(data)


def parse_html(text: str) -> Node:
    builder = _TreeBuilder()
    builder.feed(text)
    return builder.root


def find_turns(root: Node) -> list[Node]:
    key, value = TURN_ATTR
    return [n for n in root.walk() if n.attrs.get(key) == value]


# --- dates and times -------------------------------------------------------------


def tab_opened_at(text: str) -> datetime | None:
    """When the tab opened the thread, in local time — from the saved-from
    comment only: the body is full of render-time timestamps that would
    anchor every turn to the saving day."""
    saved = SAVED_FROM.search(text[:20000])
    ms = SXSRF_MS.search(saved.group(1)) if saved else None
    return datetime.fromtimestamp(int(ms.group(1)) / 1000) if ms else None


def pinned_date(text: str) -> date | None:
    m = re.search(rf'<meta name="{DATE_META}" content="(\d{{4}})-(\d{{2}})-(\d{{2}})">', text[:20000])
    return date(*map(int, m.groups())) if m else None


def first_turn_date(text: str) -> date | None:
    """DATE_META if the slim step pinned one, else the day the tab opened
    the thread."""
    opened = tab_opened_at(text)
    return pinned_date(text) or (opened.date() if opened else None)


def parse_clock(label: str) -> tuple[int, int] | None:
    """'3:53 p.m.', '3:53 PM', '15:53' -> (15, 53)."""
    m = TIME.search(label.replace(" ", " ").replace("\xa0", " "))
    if not m:
        return None
    hour, minute, half = int(m.group(1)), int(m.group(2)), (m.group(3) or "").lower()
    if half == "p" and hour != 12:
        hour += 12
    elif half == "a" and hour == 12:
        hour = 0
    return hour, minute


def assign_dates(clocks: list[tuple[int, int] | None], start: date) -> list[datetime | None]:
    """Turns are in order, so a prompt earlier in the day than the one before
    it was asked the next day. Equal minutes are the same day."""
    out: list[datetime | None] = []
    day, prev = start, None
    for clock in clocks:
        if clock is None:
            out.append(None)
            continue
        if prev is not None and clock < prev:
            day += timedelta(days=1)
        prev = clock
        out.append(datetime(day.year, day.month, day.day, clock[0], clock[1]))
    return out


# --- formulas --------------------------------------------------------------------

OPERATORS = {
    "×": r"\times", "⋅": r"\cdot", "·": r"\cdot", "≈": r"\approx", "−": "-", "→": r"\to",
    "≤": r"\le", "≥": r"\ge", "≠": r"\ne", "±": r"\pm", "∞": r"\infty", "∼": r"\sim",
    "∝": r"\propto", "…": r"\ldots", "⋯": r"\cdots", "√": r"\surd",
}
FUNCTIONS = {"sin", "cos", "tan", "cot", "log", "ln", "exp", "lim", "max", "min", "sinh", "cosh", "tanh", "det"}
LATEX_SPECIAL = {"%": r"\%", "#": r"\#", "&": r"\&", "$": r"\$"}


def _latex_chars(text: str) -> str:
    """One run of formula characters: math-alphanumeric letters folded to
    plain ones (𝜆 -> λ, 𝟎 -> 0), operators to commands, a decimal comma
    braced so LaTeX doesn't space it as punctuation."""
    out = []
    for ch in unicodedata.normalize("NFKC", text):
        if ch in OPERATORS:
            op = OPERATORS[ch]
            out.append(f" {op} " if op.startswith("\\") else op)
        else:
            out.append(LATEX_SPECIAL.get(ch, ch))
    s = "".join(out)
    return re.sub(r"(?<=\d),(?=\d)", "{,}", s)


def mathml_to_latex(node: Node) -> str:
    tag = node.tag
    kids = [k for k in node.kids if isinstance(k, Node)]
    if tag == "annotation":
        return ""
    if tag in ("mi", "mn", "mo"):
        text = unicodedata.normalize("NFKC", node.raw_text().strip())
        if tag == "mi" and len(text) > 1:
            return f"\\{text} " if text in FUNCTIONS else f"\\mathrm{{{text}}}"
        return _latex_chars(text)
    if tag == "mtext":
        return f"\\text{{{node.raw_text()}}}"
    if tag == "mspace":
        return " "
    parts = [mathml_to_latex(k) for k in kids]
    if tag == "mfrac" and len(parts) == 2:
        return f"\\frac{{{parts[0]}}}{{{parts[1]}}}"
    if tag == "msub" and len(parts) == 2:
        return f"{{{parts[0]}}}_{{{parts[1]}}}"
    if tag == "msup" and len(parts) == 2:
        return f"{{{parts[0]}}}^{{{parts[1]}}}"
    if tag == "msubsup" and len(parts) == 3:
        return f"{{{parts[0]}}}_{{{parts[1]}}}^{{{parts[2]}}}"
    if tag == "msqrt":
        return f"\\sqrt{{{''.join(parts)}}}"
    if tag == "mroot" and len(parts) == 2:
        return f"\\sqrt[{parts[1]}]{{{parts[0]}}}"
    if tag == "mover" and len(parts) == 2:
        return f"\\overset{{{parts[1]}}}{{{parts[0]}}}"
    if tag == "munder" and len(parts) == 2:
        return f"\\underset{{{parts[1]}}}{{{parts[0]}}}"
    return "".join(parts)


def _glyphs_to_latex(chip: Node) -> str:
    """A chip with no MathML: each SVG <text> is one glyph; a smaller font
    shifted up is a superscript, shifted down a subscript."""
    runs: list[tuple[str, str]] = []  # (level, chars)
    for glyph in chip.walk():
        if glyph.tag != "text":
            continue
        size = re.search(r"font-size:\s*([\d.]+)px", glyph.attrs.get("style", ""))
        shift = re.search(r"translate\(\s*[-\d.]+\s*,\s*([-\d.]+)\s*\)", glyph.attrs.get("transform", ""))
        small = size is not None and float(size.group(1)) < 0.95
        dy = float(shift.group(1)) if shift else 0.0
        level = "^" if small and dy < 0 else "_" if small and dy > 0 else ""
        if runs and runs[-1][0] == level:
            runs[-1] = (level, runs[-1][1] + glyph.raw_text())
        else:
            runs.append((level, glyph.raw_text()))
    return "".join(_latex_chars(t) if not lvl else f"{lvl}{{{_latex_chars(t).strip()}}}" for lvl, t in runs)


def chip_to_latex(chip: Node) -> str:
    maths = [n for n in chip.walk() if n.tag == "math"]
    latex = "".join(mathml_to_latex(m) for m in maths) if maths else _glyphs_to_latex(chip)
    return re.sub(r" {2,}", " ", latex).strip()


# --- response -> markdown -------------------------------------------------------

BR = "\x00"  # stands in for <br> until whitespace is collapsed


def _is_junk(node: Node) -> bool:
    return node.tag in JUNK_TAGS or bool(node.classes() & JUNK_CLASSES)


def _wrap(marker: str, inner: str) -> str:
    """'**' around the text, spaces kept outside it — '** x**' is not bold."""
    core = inner.strip(" ")
    if not core.strip():
        return inner
    lead = inner[: len(inner) - len(inner.lstrip(" "))]
    trail = inner[len(inner.rstrip(" ")):]
    return f"{lead}{marker}{core}{marker}{trail}"


def _url(href: str) -> str:
    """Parentheses and spaces would end a markdown link early."""
    return href.replace(" ", "%20").replace("(", "%28").replace(")", "%29")


def render_inline(node: Node) -> str:
    if node.has_class(CITATION_CLASS):
        link = node.find(lambda n: n.tag == "a" and n.has_class(CITATION_LINK_CLASS))
        source = node.find(lambda n: n.has_class(CITATION_SOURCE_CLASS))
        if link is None or not link.attrs.get("href"):
            return ""
        name = source.raw_text().strip() if source is not None else "source"
        return f" [{name}]({_url(link.attrs['href'])})"
    if node.has_class(CHIP_CLASS):
        latex = chip_to_latex(node)
        display = node.parent is not None and node.parent.has_class(DISPLAY_CHIP_CLASS)
        if not latex:
            return ""
        return f"{BR}{BR}$${latex}$${BR}{BR}" if display else f"${latex}$"  # a paragraph of its own
    if _is_junk(node):
        return ""
    if node.tag == "br":
        return BR
    inner = "".join(k.replace("\xa0", " ") if isinstance(k, str) else render_inline(k) for k in node.kids)
    if node.tag in ("strong", "b"):
        return _wrap("**", inner)
    if node.tag in ("em", "i"):
        return _wrap("*", inner)
    if node.tag == "code":
        return _wrap("`", inner)
    if node.tag == "a" and node.attrs.get("href", "").startswith("http") and inner.strip():
        return f"[{inner.strip()}]({_url(node.attrs['href'])})"
    return inner


def _paragraph(pieces: list[str]) -> str:
    text = re.sub(r"\s+", " ", "".join(pieces))
    lines = "\n".join(line.strip() for line in text.split(BR))
    return re.sub(r"\n{3,}", "\n\n", lines).strip()


def _indent(block: str, pad: str) -> str:
    return "\n".join(pad + line if line else line for line in block.split("\n"))


def _list(node: Node) -> str:
    items = []
    n = 0
    for li in node.kids:
        if not isinstance(li, Node) or li.tag != "li":
            continue
        n += 1
        marker = f"{n}. " if node.tag == "ol" else "- "
        blocks = render_blocks(li)
        if not blocks:
            continue
        body = "\n".join(blocks)
        first, _, rest = body.partition("\n")
        items.append(marker + first + ("\n" + _indent(rest, " " * len(marker)) if rest else ""))
    return "\n".join(items)


def _table(node: Node) -> str:
    rows = []
    for tr in (n for n in node.walk() if n.tag == "tr"):
        cells = [_paragraph([render_inline(c)]).replace("|", r"\|") for c in tr.kids if isinstance(c, Node) and c.tag in ("td", "th")]
        rows.append("| " + " | ".join(cells) + " |")
    if not rows:
        return ""
    width = rows[0].count(" | ") + 1
    return "\n".join([rows[0], "|" + " --- |" * width] + rows[1:])


def _code_block(node: Node) -> str:
    lang = node.find(lambda n: n.has_class(CODE_LANG_CLASS))
    pre = node.find(lambda n: n.tag == "pre")
    code = (pre.raw_text() if pre is not None else "").rstrip("\n")
    label = lang.raw_text().strip() if lang is not None else ""
    return f"```{label}\n{code}\n```"


def render_blocks(node: Node) -> list[str]:
    blocks: list[str] = []
    pieces: list[str] = []

    def flush():
        if pieces:
            para = _paragraph(pieces)
            if para:
                blocks.append(para)
            pieces.clear()

    for kid in node.kids:
        if isinstance(kid, str):
            pieces.append(kid.replace("\xa0", " "))
        elif kid.tag in INLINE_TAGS or kid.has_class(CITATION_CLASS) or kid.has_class(CHIP_CLASS):
            pieces.append(render_inline(kid))
        elif _is_junk(kid):
            continue
        else:
            flush()
            block = _block(kid)
            if isinstance(block, list):
                blocks.extend(block)
            elif block:
                blocks.append(block)
    flush()
    return blocks


def _block(node: Node) -> "str | list[str]":
    if node.tag in ("ul", "ol"):
        return _list(node)
    if node.tag == "blockquote":
        inner = "\n\n".join(render_blocks(node))
        return "\n".join("> " + line if line else ">" for line in inner.split("\n")) if inner else ""
    if node.tag == "hr":
        return "---"
    if node.tag == "table":
        return _table(node)
    if node.tag == "pre" or node.has_class(CODE_BLOCK_CLASS):
        return _code_block(node)
    if node.has_class(SECTION_HEADING_CLASS) or re.fullmatch(r"h[1-6]", node.tag):
        level = int(node.tag[1]) if node.tag[0] == "h" and node.tag[1:].isdigit() else 3
        title = _paragraph([render_inline(node)])
        return f"{'#' * level} {title}" if title else ""
    return render_blocks(node)


def render_response(turn: Node) -> str:
    root = turn.find(lambda n: n.has_class(RESPONSE_CLASS))
    return "\n\n".join(render_blocks(root)) if root is not None else ""


def render_prompt(turn: Node) -> str:
    heading = turn.find(lambda n: n.has_class(REPLY_HEADING_CLASS))
    text = heading.raw_text() if heading is not None else ""
    if text.startswith(REPLY_FOR):
        return text[len(REPLY_FOR):].replace("\xa0", " ").strip("\n")
    span = turn.find(lambda n: n.has_class(PROMPT_CLASS))
    return span.raw_text().replace("\xa0", " ").strip("\n") if span is not None else ""


def turn_clock(turn: Node) -> tuple[int, int] | None:
    label = turn.find(lambda n: n.has_class(TIME_CLASS))
    return parse_clock(label.raw_text()) if label is not None else None


# --- slimming ---------------------------------------------------------------------

KEEP_ATTRS = {"class", "href", "encoding", "data-scope-id"}
KEEP_GLYPH_ATTRS = {"style", "transform"}


def _serialize(node: Node, in_citation: bool = False, in_chip: bool = False) -> str:
    """Only what render_prompt/render_response/turn_clock read survives —
    junk subtrees, icons, images and attributes go; chips keep their MathML
    and glyph <text>s, citations their link and source name."""
    tag = node.tag
    in_citation = in_citation or node.has_class(CITATION_CLASS)
    in_chip = in_chip or node.has_class(CHIP_CLASS)
    if in_chip and tag in ("svg", "g", "text"):
        pass
    elif in_citation and tag == "button":
        pass
    elif _is_junk(node) or (in_chip and tag in ("path", "rect", "line", "polygon", "circle", "defs", "clippath")):
        return ""
    inner = "".join(html.escape(k, quote=False) if isinstance(k, str) else _serialize(k, in_citation, in_chip) for k in node.kids)
    keep = KEEP_ATTRS | (KEEP_GLYPH_ATTRS if tag == "text" else set())
    attrs = "".join(f' {k}="{html.escape(v, quote=True)}"' for k, v in node.attrs.items() if k in keep)
    if tag in VOID:
        return f"<{tag}{attrs}>" if tag in ("br", "hr") else ""
    if not inner and tag not in ("td", "th", "tr") and not (tag == "a" and node.attrs.get("href")):
        return ""  # a citation's link is empty but carries the url
    return f"<{tag}{attrs}>{inner}</{tag}>"


def slim(text: str, pinned: date | None = None) -> str:
    root = parse_html(text)
    saved = SAVED_FROM.search(text[:20000])
    title = root.find(lambda n: n.tag == "title")
    start = pinned or pinned_date(text)  # a pin survives re-slimming a slim copy
    head = ['<meta charset="utf-8">']
    if title is not None:
        head.append(f"<title>{html.escape(title.raw_text(), quote=False)}</title>")
    if start is not None:
        head.append(f'<meta name="{DATE_META}" content="{start:%Y-%m-%d}">')
    body = "\n".join(_serialize(t) for t in find_turns(root))
    lines = ["<!DOCTYPE html>"]
    if saved:
        lines.append(saved.group(0))
    lines.append(f"<html><head>{''.join(head)}</head><body>")
    lines.append(body)
    lines.append("</body></html>")
    return "\n".join(lines) + "\n"


# --- source interface -----------------------------------------------------------


def detect(path: Path) -> bool:
    if path.suffix.lower() not in (".html", ".htm"):
        return False
    key, value = TURN_ATTR
    return f'{key}="{value}"' in path.read_text(encoding="utf-8", errors="replace")


def load_atoms(path: Path) -> list[Atom]:
    text = path.read_text(encoding="utf-8")
    turns = find_turns(parse_html(text))
    start = first_turn_date(text)
    clocks = [turn_clock(t) for t in turns]
    if start is None:
        print(f"warning: {path.name}: no date on the page (no saved-from comment, no {DATE_META}); turns left undated", file=sys.stderr)
        stamps: list[datetime | None] = [None] * len(turns)
    else:
        stamps = assign_dates(clocks, start)
    atoms: list[Atom] = []
    for turn, stamp in zip(turns, stamps):
        atoms.append(Atom("prompt", text=render_prompt(turn), timestamp=stamp))
        atoms.append(Atom("response", text=render_response(turn)))
    return atoms
